### ISSUE TITLE
question about world protect borders

### ISSUE THREAD

**Issue by timbersquirrel** [poggit-orphanage/office#18]
I tried to set borders by doing /wp border 10000 10000 -10000 -10000
even if im not op i can still move past it... i dont understand

**Comment by Awzaw** [comment]
https://github.com/poggit-orphanage/WorldProtect/blob/dev/README.md

/wp border x1 z1 x2 z2

**Comment by timbersquirrel** [comment]
Yeah it didn’t work

**Comment by Awzaw** [comment]
Please post the exact command you used, because it's working fine for me. You did enable   `border: true` under `features` in the WorldProtect config?

**Comment by timbersquirrel** [comment]
I don’t think I have (border: true) set to true but I can’t find it in the reasorces

**Comment by Awzaw** [comment]
config.yml should look something like this:
```
---
version: 2.3.0
motd:
  '# ticks': line delay when showing multi-line motd texts.
  ticks: 15
  '# auto-motd': Automatically shows motd when entering world
  auto-motd: true
features:
  max-players: false
  protect: true
  border: true
  pvp: true
  motd: false
  no-explode: true
  unbreakable: false
  bancmds: false
  banitem: true
  gamemode: true
  gm-save-inv: true
  death-save-inv: true
...
```
